#!/bin/sh
# chkconfig: 345 99 01
# description: Oracle auto start-stop script.
#
# Set ORA_HOME to be equivalent to the $ORACLE_HOME
# from which you wish to execute dbstart and dbshut;
#
# Set ORA_OWNER to the user id of the owner of the
# Oracle database in ORA_HOME.

### BEGIN INIT INFO
# Provides: dbora
# Required-Start: $local_fs $network sshd
# Required-Stop: $local_fs $network sshd
# Default-Start:  3 4 5
# Default-Stop: 0 1 6
# Short-Description: Oracle Database and TNS listener
# Description: Oracle Database and TNS listener
### END INIT INFO

ORA_OWNER=oracle
ORA_HOME=/u01/app/oracle/product/12.1.0/dbhome_1
case "$1" in
    'start')
     # Start the Oracle databases:
        su $ORA_OWNER -c "$ORA_HOME/bin/dbstart"
        #To start the non-default listener set listener oracle home
        ORACLE_HOME=/u01/app/oracle/product/12.1.0/dbhome_1
        export ORACLE_HOME
        su $ORA_OWNER -c "$ORACLE_HOME/bin/lsnrctl stop"
        su $ORA_OWNER -c "$ORACLE_HOME/bin/lsnrctl start LISTENER"
        if [ -d /var/lock/subsys ] ; then
          touch /var/lock/subsys/dbora
        fi
        ;;
    'stop')
        # Stop the Oracle databases:
        su $ORA_OWNER -c "$ORA_HOME/bin/dbshut"
        #To stop the non-default listener set listener oracle home
        ORACLE_HOME=/u01/app/oracle/product/12.1.0/dbhome_1
        export ORACLE_HOME
        su $ORA_OWNER -c "$ORACLE_HOME/bin/lsnrctl stop LISTENER"
        rm -f /var/lock/subsys/dbora
        ;;
esac
